import canonicalize from 'canonicalize';

export interface Env { HYPERDRIVE: Hyperdrive; MAIL_RELAY_URL: string; API_SECRET: string; MAIL_FROM: string; MAIL_SIGNING_PRIVATE_KEY: string; MAIL_SIGNING_KEY_ID: string; SOURCE_ID_PEPPER: string; ACCOUNT_ID_PEPPER: string; CORS_ORIGIN?: string; OTP_PEPPER?: string; }
export interface DeliveryRequest { version:'1'; keyId:string; requestId:string; issuedAt:number; expiresAt:number; accountId:string; sourceId:string; recipient:string; from:string; templateId:'login-code-v1'; message:{subject:string;text:string}; messageHash:string; }
export function corsAllowed(origin:string,env:Env){return (env.CORS_ORIGIN??'').split(',').map(s=>s.trim()).includes(origin);}
export function json(req:Request,env:Env,body:unknown,status=200){const r=Response.json(body,{status});const o=req.headers.get('Origin');if(o&&corsAllowed(o,env))r.headers.set('Access-Control-Allow-Origin',o);r.headers.set('Vary','Origin');return r;}
export function corsPreflight(req:Request,env:Env){const r=new Response(null,{status:204});const o=req.headers.get('Origin');if(o&&corsAllowed(o,env))r.headers.set('Access-Control-Allow-Origin',o);r.headers.set('Access-Control-Allow-Methods','GET, POST, OPTIONS');r.headers.set('Access-Control-Allow-Headers','Content-Type, Authorization');return r;}
export async function readJson(req:Request):Promise<Record<string,unknown>|null>{try{const b=await req.json();return b&&typeof b==='object'?b as Record<string,unknown>:null;}catch{return null;}}
export async function sha256Hex(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
export function timingSafeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
export function genOtpCode(){const b=new Uint32Array(1);crypto.getRandomValues(b);return String((b[0]!%900000)+100000);}
export function genToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
export function uuidv4(){return crypto.randomUUID();}
export function canonicalBytes(v:unknown){const t=canonicalize(v);if(!t)throw new Error('canonical');return new TextEncoder().encode(t);}
function b64url(b:ArrayBuffer){return btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function key(raw:string){const b=Uint8Array.from(atob(raw.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));return crypto.subtle.importKey('pkcs8',b,'Ed25519',false,['sign']);}
export async function opaqueId(p:string,v:string){return sha256Hex(`${p}:${v}`);}
export async function makeDeliveryRequest(env:Env,to:string,code:string,source:string){const message={subject:'کد ورود mTracker',text:`${code} کد ورود شماست. ۱۰ دقیقه اعتبار دارد.`};const now=Date.now();const request:DeliveryRequest={version:'1',keyId:env.MAIL_SIGNING_KEY_ID,requestId:uuidv4(),issuedAt:now,expiresAt:now+120000,accountId:await opaqueId(env.ACCOUNT_ID_PEPPER,to),sourceId:await opaqueId(env.SOURCE_ID_PEPPER,source),recipient:to,from:env.MAIL_FROM,templateId:'login-code-v1',message,messageHash:await sha256Hex(canonicalize(message)!)};const signature=b64url(await crypto.subtle.sign('Ed25519',await key(env.MAIL_SIGNING_PRIVATE_KEY),canonicalBytes(request)));return {request,signature};}
export async function sendDeliveryRequest(env:Env,request:DeliveryRequest,signature:string):Promise<{ok:true}|{ok:false}>{try{const r=await fetch(env.MAIL_RELAY_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${env.API_SECRET}`,'X-Mail-Signature':signature},body:JSON.stringify(request)});return r.ok?{ok:true}:{ok:false};}catch{return {ok:false};}}
export async function sendOtpMail(env:Env,to:string,code:string,source='unknown'):Promise<{ok:true;requestId:string}|{ok:false}>{const {request,signature}=await makeDeliveryRequest(env,to,code,source);const result=await sendDeliveryRequest(env,request,signature);return result.ok?{ok:true,requestId:request.requestId}:{ok:false};}
