/* main-mail: direct-deployment, database-free, signed login-code relay. */
const enc=new TextEncoder();
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
function b64(s){try{return Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));}catch{return null;}}
function canon(v){if(v===null||typeof v==='boolean'||typeof v==='number')return JSON.stringify(v);if(typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canon).join(',')}]`;if(typeof v==='object')return `{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')}}`;throw Error('invalid');}
async function hash(v){const d=await crypto.subtle.digest('SHA-256',enc.encode(canon(v)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function reply(ok,status,id){return Response.json({ok,correlationId:id},{status});}
function event(type,id,keyId){console.log(JSON.stringify({event:type,correlationId:id,keyId}));}
async function publicKey(env,id){let raw,until=Infinity;if(id===env.MAIL_SIGNING_KEY_ID)raw=env.MAIL_SIGNING_PUBLIC_KEY;else if(id===env.MAIL_PREVIOUS_KEY_ID){raw=env.MAIL_PREVIOUS_PUBLIC_KEY;until=Number(env.MAIL_PREVIOUS_KEY_EXPIRES_AT);}else return null;if(!raw||Date.now()>until)return null;const b=b64(raw);return b&&crypto.subtle.importKey('spki',b,'Ed25519',false,['verify']);}
function valid(b,env){return b&&b.version==='1'&&typeof b.keyId==='string'&&typeof b.requestId==='string'&&typeof b.issuedAt==='number'&&typeof b.expiresAt==='number'&&b.expiresAt>b.issuedAt&&b.expiresAt-b.issuedAt<=120000&&typeof b.accountId==='string'&&typeof b.sourceId==='string'&&typeof b.recipient==='string'&&EMAIL.test(b.recipient)&&b.from===env.MAIL_FROM&&b.templateId==='login-code-v1'&&b.message&&b.message.subject==='کد ورود mTracker'&&typeof b.message.text==='string'&&/^\d{6} کد ورود شماست\. ۱۰ دقیقه اعتبار دارد\.$/.test(b.message.text)&&typeof b.messageHash==='string';}
export default {async fetch(req,env){const id=crypto.randomUUID();const u=new URL(req.url);if(req.method==='GET'&&u.pathname==='/health')return Response.json({ok:true});if(req.method!=='POST'||u.pathname!=='/send'||u.protocol!=='https:')return reply(false,400,id);try{const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer ')||!equal(auth.slice(7),env.API_SECRET))throw Error('reject');const b=await req.json();if(!valid(b,env)||Date.now()<b.issuedAt-60000||Date.now()>b.expiresAt+60000||!equal(await hash(b.message),b.messageHash))throw Error('reject');const key=await publicKey(env,b.keyId),sig=b64(req.headers.get('X-Mail-Signature')||'');if(!key||!sig||!await crypto.subtle.verify('Ed25519',key,sig,enc.encode(canon(b))))throw Error('reject');const rk=`replay:${b.requestId}`;if(await env.MAIL_REPLAY_KV.get(rk)){event('replayed',id,b.keyId);throw Error('reject');}await env.MAIL_REPLAY_KV.put(rk,id,{expirationTtl:300});const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:b.from,to:b.recipient,subject:b.message.subject,text:b.message.text})});if(!r.ok){event('provider_failed',id,b.keyId);return reply(false,502,id);}event('accepted',id,b.keyId);return reply(true,202,id);}catch{event('rejected',id,null);return reply(false,400,id);}}};
